apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: masterdeploy
spec:
  destination:
    name: ''
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: GitOpsInfra
    repoURL: 'https://github.com/AlphaF22A/GitOps-Alpha/'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
