apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-pipeline
spec:
  destination:
    name: ''
    namespace: pipeline
    server: https://kubernetes.default.svc
  source:
    path: /Pipeline
    repoURL: https://github.com/AlphaF22A/GitOps-Alpha
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
